theme: jekyll-theme-cayman
# global settings
title: "EQdkp Plus"
description: "Easy Raid- and Guildmanagement - with EQdkp Plus"

show_downloads: true
github:
  zip_url: https://eqdkpplus.github.io/packages/core/fullpackage.zip
  tar_url: https://eqdkpplus.github.io/packages/core/fullpackage.zip
